# Dev environment values for the color-app chart.
replicaCount: 1

image:
  repository: 905740063985.dkr.ecr.us-east-1.amazonaws.com/color-app
  pullPolicy: IfNotPresent
  tag: "v2"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  name: eso-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::905740063985:role/color-app-eso-role

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: LoadBalancer
  port: 80
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

namespace:
  create: false
  name: dev

configMap:
  enabled: true
  data:
    APP_COLOR: green
    APP_ENV: dev
    APP_MESSAGE: "Welcome to the Dev Color App!"

secret:
  enabled: true
  name: color-app-secret
  stringData: {}

externalSecret:
  enabled: true
  refreshInterval: 1m
  secretStore:
    service: SecretsManager
    region: us-east-1
    serviceAccountRef:
      name: ""
  secretStoreRef:
    name: color-app-ss
    kind: SecretStore
  target:
    name: color-app-secret
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: color-app/dev
        property: SECRET_KEY
    - secretKey: DB_PASSWORD
      remoteRef:
        key: color-app/dev
        property: DB_PASSWORD
    - secretKey: API_KEY
      remoteRef:
        key: color-app/dev
        property: API_KEY

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClassName: gp2
  mountPath: /usr/src/app/data

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - chart-example.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

reloader:
  enabled: true
