{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" (include "color-app.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "color-app.namespace" . }}
  labels:
    {{- include "color-app.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}