{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecret.secretStoreRef.name }}
  namespace: {{ include "color-app.namespace" . }}
  labels:
    {{- include "color-app.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: {{ .Values.externalSecret.secretStore.service }}
      region: {{ .Values.externalSecret.secretStore.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ default (include "color-app.serviceAccountName" .) .Values.externalSecret.secretStore.serviceAccountRef.name | quote }}
{{- end }}