{{- if and .Values.secret.enabled (not .Values.externalSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default (printf "%s-secret" (include "color-app.fullname" .) | trunc 63 | trimSuffix "-") | quote }}
  namespace: {{ include "color-app.namespace" . }}
  labels:
    {{- include "color-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secret.stringData | nindent 2 }}
{{- end }}